### ISSUE TITLE
LPM principal Use not updated

### ISSUE THREAD

**Issue by gvaibhavraj2** [AltraMayor/XIA-for-Linux#13]
Implementation of LPM is not described on https://github.com/AltraMayor/XIA-for-Linux/wiki/4ID-principals 
It still shows "Status: not yet implemented".

**Comment by AltraMayor** [comment]
Thank you for pointing that out.

The LPM principal was merged into Linux XIA on February 10th, 2016. So we haven't had time to document much about it. Basic information about how to use the LPM principal is available on the link below, though.

https://github.com/AltraMayor/XIA-for-Linux/wiki/How-to-set-up#lpm-principal

If you can construct an experiment for the LPM principal using the U4ID experiment as a starting point, and write it up, we'd be interested in adding your text to the LPM section.

**Comment by gvaibhavraj2** [comment]
@AltraMayor I was already thinking of doing the same after completion of my Gsoc proposal, right now working on it and going through all the code and documentation.

**Comment by vineetparikh** [comment]
By the way, I just started working on the documentation for the LPM principal. Sorry if there is any inconvenience.

**Comment by AltraMayor** [comment]
Hi @vineetparikh,

That's great! We'll be excited to add this documentation to our wiki.

I suggest you to use Google docs to allow people to review/edit you document before we merge it into the wiki.

**Comment by vineetparikh** [comment]
Hello @AltraMayor 

I added the Google Doc with the documentation onto XIA's Google Group.

**Comment by cjdoucette** [comment]
Vineet has completed the LPM documentation, which I just added to the wiki on his behalf:

https://github.com/AltraMayor/XIA-for-Linux/wiki/4ID-principals#LPM

I've reviewed it, so if it looks OK to you Michel then I think this issue can be closed. Thanks Vineet!

**Comment by AltraMayor** [comment]
Great work @vineetparikh and @cjdoucette!

I have one question: shouldn't prefix length 10 in the example be 12? Consider this command from the example:
`# xip lpm addroute 0x90b0000000000000000000000000000000000000 10 gw HID_host`
The expression 0x90b has 12 bits.

The whole example works fine because there's no conflict on those two bits out of the mask, but I decided to comment here because this small issue can confuse other people trying the experiment.

If I'm correct, the length 10 must be changed in 3 places in the documentation.

**Comment by vineetparikh** [comment]
Hey @AltraMayor:

I checked to make sure, and you are totally right: 0x90b has 12 bits instead of 10. I fixed all occurrences in which that occurred within the documentation on my branch's wiki. I'm unable to change the wiki on this branch though, so could you please (if possible) merge my branch wiki edits into this branch?

Thanks so much,
Vineet

**Comment by AltraMayor** [comment]
Hi @vineetparikh,

I've reviewed the text on the wiki to replace all occurrences of 10 (or "ten") as a prefix to 12. If you find that I missed a spot or yet another issue, please open a new issue here on GitHub.

Thank you for the contribution. I'm sure that other students will appreciate it.
